---
- name: Set physical interfaces
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ item.interface }}"
      description: "{{ item.description }}"
      enabled: "{{ item.enabled }}"
    state: merged
  loop: "{{ interfaces }}"
  when: "'loopback' not in item.interface | lower"

- name: Apply No Switchport for L3 interfaces
  cisco.ios.ios_config:
    lines:
    - no switchport
    parents: interface {{ item.interface }}
  loop: "{{ interfaces }}"
  when: 
    - item.description != "MGMT"
    - item.enabled == True 
    - item.address != None
    - "'Ethernet' in item.interface"

- name: Assign VRF for L3 interfaces
  cisco.ios.ios_config:
    lines:
      - ip vrf forwarding {{ item.vrf }}
    parents: interface {{ item.interface }}
  loop: "{{ interfaces }}"
  when: 
    - item.description != "MGMT"
    - item.enabled == True 
    - item.address != None
    - "'Ethernet' in item.interface"

- name: L3 Interfaces configuration
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ item.interface }}"
        ipv4:
          - address: "{{ item.address }}{{ item.mask }}"
    state: merged
  loop: "{{ interfaces }}"
  when: 
    - item.description != "MGMT"
    - item.enabled == True
    - item.address is not none
    - "'Ethernet' in item.interface"

