---
- name: Gather facts (ios)
  cisco.ios.ios_facts:
    gather_subset:
    - config
    gather_network_resources:
    - l3_interfaces
  register: res_facts

# - name: Display some facts
#   debug:
#     var: res_facts.ansible_facts