---
- name: Set interfaces settings
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ item.interface }}"
      description: "{{ item.description }}"
      enabled: "{{ item.enabled }}"
    state: merged
  loop: "{{ interfaces }}"
  # when: 
  # - item.enabled == True 

# - name: Merge provided configuration with device L2 interfaces
#   cisco.ios.ios_l2_interfaces:
#     config:
#       - name: "{{ item.interface }}"
#         mode: "{{ item.interface_mode }}"
#         access:
#           vlan: "{{ item.vlan }}"
#     state: merged
#   loop: "{{ interfaces }}"
#   when:
#     - item.layer_mode == "layer2" and item.vlan != None

- name: Merge provided configuration with device L3 interfaces
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ item.interface }}"
        ipv4:
          - address: "{{ item.ipv4 }}"
  loop: "{{ interfaces }}"
  when:
    - item.layer_mode == "layer3" and item.ipv4 != "dhcp"

# - name: Merge provided configuration with device L3 interfaces dhcp
#   cisco.ios.ios_l3_interfaces:
#     config:
#       - name: "{{ item.interface }}"
#         ipv4:
#           - dhcp:
#               enable: true
#   loop: "{{ interfaces }}"
#   when:
#     - item.layer_mode == "layer3" and item.ipv4 == "dhcp"