---
- name: Display some facts
  debug:
    var: res_facts.ansible_facts.ansible_network_resources.l3_interfaces

- name: Set loopback interfaces ONLY if IPv4 not already present
  cisco.ios.ios_config:
    lines:
      - "description {{ item.description }}"
      - "ip vrf forwarding {{ item.vrf }}"
      - "ip address {{ item.address }} {{ item.mask }}"
    parents: interface {{ item.interface }}
  loop: "{{ interfaces }}"
  when:
    - "'loopback' in item.interface | lower"
